name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONDITION: ${{ github.event_name == 'push' && ! contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Render Deploy Action
        if: ${{ env.CONDITION == 'true' }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.POKEDEX_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Test Success
        uses: stegzilla/discord-notify@v4
        if: ${{ success() && env.CONDITION == 'true' }}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: A new version of Pokedex deployed
          message: "to https://full-stack-open-pokedex-au14.onrender.com/ by ${{ github.event.pusher.name }}"
          colour: "#00ff00"

      - name: Test Failure
        uses: stegzilla/discord-notify@v4
        if: ${{ failure() && env.CONDITION == 'true'  }}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Build failed
          message: "commit ${{ github.event.head_commit.url }} by ${{ github.event.pusher.name }} broke the build :("
          colour: "#ff0000"

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        if: ${{ env.CONDITION == 'true' }}
      - name: Bump version and push tag
        if: ${{ env.CONDITION == 'true' }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
